// src/ui/Nav.tsx
import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/dist/client/router';
import { CloseIcon, MenuIcon } from '~/icons';
import { ThemeSwitcher } from './ThemeSwitcher';

interface NavProps {}

interface NavLinkProps {
  title: string;
  path: string;
}

const Nav: React.FC<NavProps> = ({}) => {
  const [open, setOpen] = useState(false);

  return (
    <nav className="w-full sticky mb-2 top-0 bg-gray-100 bg-opacity-75 dark:bg-primary-900 dark:bg-opacity-75 backdrop-saturate-150 backdrop-blur-xl z-10">
      <div className="flex max-w-screen-xs mx-auto py-5 px-6">
        <Link href="/">
          <a className="flex items-center mr-3.5">
            <div className="text-black dark:text-primary-100 text-xl">
              <span className="font-bold">Jakub</span>
              <span>H</span>
            </div>
          </a>
        </Link>

        <ThemeSwitcher />

        <ul className="hidden md:flex items-center ml-auto">
          <NavLink title="Home" path="/" />
          <NavLink title="About" path="/about" />
          <NavLink title="Projects" path="/projects" />
          <NavLink title="Contact" path="/contact" />
        </ul>

        <button
          aria-label="Menu Button"
          className="md:hidden ml-auto text-xl"
          onClick={() => setOpen(!open)}
        >
          {open ? <CloseIcon /> : <MenuIcon />}
        </button>
      </div>

      {open && (
        <ul className="flex md:hidden items-center flex-col max-w-screen-xs mx-auto mb-6 px-6">
          <NavLink title="Home" path="/" />
          <NavLink title="About" path="/about" />
          <NavLink title="Projects" path="/projects" />
          <NavLink title="Contact" path="/contact" />
        </ul>
      )}
    </nav>
  );
};

export const NavLink: React.FC<NavLinkProps> = ({ title, path }) => {
  const router = useRouter();
  const isActive = router.asPath === path;

  return (
    <li className="w-full py-4 border-b md:border-none border-primary-600 md:w-auto md:p-0 md:ml-5">
      <Link href={path}>
        <a
          className={`font-medium transition-colors duration-200 ${
            isActive
              ? 'text-secondary-accent hover:text-secondary-accent-hover'
              : 'text-gray-700 dark:text-primary-100 hover:text-secondary-accent dark:hover:text-secondary-accent'
          }`}
        >
          {title}
        </a>
      </Link>
    </li>
  );
};

export default Nav;

// src/lib/components/nav/Nav.svelte
<script>
	import Transition from 'svelte-transition';
	import MenuIcon from '../svg/icons/menu.svg?component';
	import ThemeSwitcher from '../ThemeSwitcher.svelte';
	import NavLink from './NavLink.svelte';
	import { beforeNavigate } from '$app/navigation';
	import { removeScroll } from '$lib/actions/removeScroll';

	let expanded = false;

	const links = [
		{ href: '/', label: 'Home' },
		{ href: '/about', label: 'About' },
		{ href: '/projects', label: 'Projects' },
		{ href: '/contact', label: 'Contact' }
	];

	beforeNavigate(() => {
		expanded = false;
	});
</script>

<nav
	class="sticky top-0 z-50 mx-auto mb-2 flex w-full max-w-screen-sm items-center justify-between bg-white px-4 py-4 dark:bg-black"
>
	<div class="flex items-center gap-4">
		<a class="flex items-center" href="/">
			<div class="text-lg">
				<span class="font-bold">Jakub</span><span>H</span>
			</div>
		</a>
		<ThemeSwitcher />
	</div>

	<ul class="ml-auto hidden items-center gap-1.5 md:flex">
		{#each links as { href, label }}
			<NavLink {href}>{label}</NavLink>
		{/each}
	</ul>

	<button
		title={expanded ? 'Close sidebar' : 'Open sidebar'}
		aria-label={expanded ? 'Close sidebar' : 'Open sidebar'}
		on:click={() => (expanded = !expanded)}
		class="block p-1 md:hidden"
	>
		<MenuIcon class="h-6 w-6" />
	</button>
</nav>

<Transition show={expanded}>
	<div use:removeScroll={{ disable: !expanded }} class="fixed inset-0 top-16 z-50 flex md:hidden">
		<Transition
			enter="transition ease-in-out duration-300 transform"
			enterFrom="translate-x-full"
			enterTo="translate-x-0"
			leave="transition ease-in-out duration-300 transform"
			leaveFrom="translate-x-0"
			leaveTo="translate-x-full"
		>
			<aside class="h-full w-full bg-white dark:bg-black">
				<ul class="mx-auto flex max-w-screen-sm flex-col gap-1.5 px-4">
					{#each links as { href, label }}
						<NavLink {href} class="px-3.5 py-2.5 text-base">{label}</NavLink>
					{/each}
				</ul>
			</aside>
		</Transition>
	</div>
</Transition>
