// src/modules/about/ExperienceRow.tsx
import React from 'react';
import { format, intervalToDuration } from 'date-fns';

interface ExperienceRowPros {
  companyName: string;
  companySite: string;
  employmentType: string;
  title: string;
  startDate: string;
  endDate?: string;
}

export const formatDuration = (start: Date, end: Date) => {
  const duration = intervalToDuration({ start, end });

  return Object.entries(duration)
    .reduce<string[]>((result, [duration, value]) => {
      if (value <= 0) return result;

      if (duration === 'years') result.push(`${value} yr`);
      if (duration === 'months') result.push(`${value} mos`);

      return result;
    }, [])
    .join(' ');
};

export const ExperienceRow: React.FC<ExperienceRowPros> = ({
  companyName,
  companySite,
  employmentType,
  title,
  startDate,
  endDate
}) => {
  const DATE_FORMAT = 'MMM yyyy';

  const duration = formatDuration(
    new Date(startDate),
    endDate ? new Date(endDate) : new Date()
  );

  return (
    <div className="group flex items-center space-x-4">
      <div>
        <a
          target="_blank"
          rel="noreferrer noopener"
          href={companySite}
          className="text-primary-100 transition-colors hover:text-secondary-accent hover:underline"
        >
          {companyName}
        </a>
        <span> · {employmentType}</span>
      </div>
      <div className="flex-1 shrink border-t border-dashed border-primary-300 dark:border-primary-600" />
      <div className="mr-6 font-medium text-primary-100">{title}</div>
      <div className="text-sm text-primary-200">
        <span>{format(new Date(startDate), DATE_FORMAT)}</span>
        {' - '}
        {endDate ? format(new Date(endDate), DATE_FORMAT) : 'Present'}
        {duration ? ' · ' + duration : null}
      </div>
    </div>
  );
};

// src/routes/(main)/about/_components/ExperienceRow.svelte
<script lang="ts" module>
	import { intervalToDuration } from 'date-fns';
	import { pluralize } from '$lib/utils/pluralize';

	export const formatDuration = (start: Date, end: Date) => {
		const { years, months, days } = intervalToDuration({ start, end });

		return [
			years && `${years} ${pluralize(years, 'yr')}`,
			months && `${months} ${pluralize(months, 'mo')}`,
			days && `${days} ${pluralize(days, 'day')}`
		]
			.filter(Boolean)
			.join(' ');
	};
</script>

<script lang="ts">
	import { format } from 'date-fns';
	import type { Component } from 'svelte';
	import Description from '$lib/components/Description.svelte';
	import Link from '$lib/components/Link.svelte';
	import Headline from '$lib/components/nav/Headline.svelte';

	type Props = {
		companyName: string;
		companyLogo: Component;
		companyColor: string;
		companySite: string;
		employmentType: string;
		title: string;
		startDate: string;
		endDate?: string;
	};

	let {
		companyName,
		companyLogo: CompanyLogo,
		companyColor,
		companySite,
		employmentType,
		title,
		startDate,
		endDate
	}: Props = $props();

	const DATE_FORMAT = 'MMM yyyy';

	const duration = formatDuration(new Date(startDate), endDate ? new Date(endDate) : new Date());
</script>

<li class="flex flex-col">
	<div class="mb-3 flex items-center gap-3">
		<div class="rounded-lg p-2" style="background-color: {companyColor}22;">
			<CompanyLogo class="h-5 w-5" />
		</div>

		<Link href={companySite} title={companyName} class="text-base font-medium hover:underline">
			{companyName}
		</Link>
	</div>

	<div class="mb-2">
		<Headline level="3" class="mb-0.5 text-base!">
			{title} · {employmentType}
		</Headline>
		<Description as="div" class="text-xs text-neutral-400">
			<span>{format(new Date(startDate), DATE_FORMAT)}</span>
			-
			{endDate ? format(new Date(endDate), DATE_FORMAT) : 'Present'}
			{duration ? ' · ' + duration : null}
		</Description>
	</div>
</li>
