// src/modules/about/WorkExperience.tsx
import React from 'react';
import { workExperiences } from '~/lib/constants';
import { ExperienceRow } from './ExperienceRow';

const WorkExperience: React.FC = () => (
  <div className="flex flex-col">
    <h3 className="mb-3 text-xl font-medium text-black dark:text-primary-100">
      Work Experience
    </h3>

    <div className="flex flex-col gap-1.5">
      {workExperiences.map((experience, i) => (
        <ExperienceRow key={i} {...experience} />
      ))}
    </div>
  </div>
);

export default WorkExperience;

// src/routes/(main)/about/_components/WorkExperience.svelte
<script lang="ts">
	import ExperienceRow from './ExperienceRow.svelte';
	import Headline from '$lib/components/nav/Headline.svelte';
	import { workExperiences } from '$lib/constants';
</script>

<section class="flex flex-col">
	<Headline level="2" class="mb-3">Work experience</Headline>
	<ul class="flex flex-col gap-4">
		{#each workExperiences as experience}
			<ExperienceRow {...experience} />
		{/each}
	</ul>
</section>
