// src/routes/projects/+page.svelte
<script lang="ts">
	import Description from '$lib/components/Description.svelte';
	import Seo from '$lib/components/Seo.svelte';
	import Headline from '$lib/components/nav/Headline.svelte';
	import Projects from './Projects.svelte';
</script>

<div class="mb-5">
	<Headline level="1" class="mb-3">My Projects</Headline>
	<Description>
		I've made a lot of projects and this is a small selection of some that I found interesting.
	</Description>
</div>

<Projects />

<Seo
	title="Projects / Jakub Habrcetl"
	description="I can turn your idea into a fully working project. Here are some examples."
/>

// src/pages/projects/index.tsx
import Container from '~/ui/Container';
import ProjectThumbnail from '~/modules/projects/ProjectThumbnail';
import PageHeading from '~/ui/PageHeading';
import { allProjects } from 'contentlayer/generated';
import type { InferGetStaticPropsType } from 'next';

const Projects = ({
  projects
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Container
      meta={{
        title: 'Projects / Jakub Habrcetl',
        description:
          'I can turn your idea into a fully working project. Here are some examples.'
      }}
    >
      <div className="max-w-screen-xs mx-auto px-6 mb-16">
        <PageHeading
          title="My Projects"
          description="I've made a lot of projects and this is a small selection of some that I found interesting."
        />
      </div>

      <div className="max-w-4xl px-6 mx-auto">
        <div className="grid grid-cols-[repeat(auto-fill,_minmax(320px,_1fr))] gap-9">
          {projects.map((project) => (
            <ProjectThumbnail key={project._id} project={project} />
          ))}
        </div>
      </div>
    </Container>
  );
};

export default Projects;

export function getStaticProps() {
  return {
    props: {
      projects: allProjects.sort(
        (a, b) =>
          new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
      )
    }
  };
}
