// src/routes/about/MusicTrack.svelte
<script lang="ts">
	import clsx from 'clsx';
	import PlayIcon from '$lib/components/svg/icons/play.svg?component';
	import PauseIcon from '$lib/components/svg/icons/pause.svg?component';

	export let order: number;
	export let artist: string;
	export let title: string;
	export let audioUrl: string;
	export let thumbnailUrl: string;
	export let isPlaying: boolean;
</script>

<div class="flex max-w-full flex-row items-center">
	<div
		class="mr-4 hidden w-5 flex-none place-content-center text-sm text-gray-600 dark:text-neutral-400 sm:grid"
	>
		{String('0' + order).slice(-2)}
	</div>

	<img
		alt="Track cover"
		class="h-10 w-10 flex-none overflow-hidden rounded-md bg-neutral-100"
		src={thumbnailUrl}
	/>

	<div class="mx-4 w-full overflow-hidden">
		<div
			class="mb-0.5 truncate text-sm font-medium text-neutral-900 dark:text-zinc-50 md:text-base"
		>
			{title}
		</div>
		<div class="-mt-1 truncate text-sm text-zinc-400 dark:text-zinc-400">
			{artist}
		</div>
	</div>

	{#if audioUrl}
		<button
			type="button"
			class="relative ml-auto flex-none w-5 h-5 text-neutral-900 dark:text-zinc-50"
			aria-label={`${isPlaying ? 'Pause' : 'Play'} ${title} by ${artist}`}
			on:click
		>
			<PauseIcon
				class={clsx(
					'absolute top-0 left-0 transition-opacity',
					isPlaying ? 'opacity-100' : 'opacity-0'
				)}
			/>
			<PlayIcon
				class={clsx(
					'absolute top-0 left-0 transition-opacity',
					isPlaying ? 'opacity-0' : 'opacity-100'
				)}
			/>
		</button>
	{/if}
</div>

// src/modules/about/MusicTrack.tsx
import React from 'react';
import Image from 'next/image';
import { PlayIcon, PauseIcon } from '~/icons';

interface MusicTrackProps {
  order: number;
  artist: string;
  title: string;
  audioUrl: string;
  thumbnailUrl: string;
  isPlaying: boolean;
  onToggle: () => void;
}

const MusicTrack: React.FC<MusicTrackProps> = ({
  order,
  artist,
  title,
  audioUrl,
  thumbnailUrl,
  isPlaying,
  onToggle
}) => {
  return (
    <div className="max-w-full flex flex-row items-center">
      <div className="text-sm hidden sm:grid flex-none place-content-center w-5 mr-6 text-gray-600 dark:text-primary-300">
        {String('0' + order).slice(-2)}
      </div>

      <Image
        width={64}
        height={64}
        alt="Track cover"
        className="h-12 w-12 flex-none rounded-md overflow-hidden bg-gray-100 dark:bg-primary-800"
        src={thumbnailUrl}
      />

      <div className="w-full mx-4 overflow-hidden">
        <div className="font-medium text-sm md:text-base truncate mb-0.5 text-black dark:text-primary-100">
          {title}
        </div>
        <div className="-mt-1 text-sm truncate text-gray-600 dark:text-primary-200">
          {artist}
        </div>
      </div>

      {audioUrl ? (
        <button
          type="button"
          onClick={onToggle}
          className="ml-auto text-gray-800 dark:text-primary-100 hover:scale-105"
          aria-label={isPlaying ? 'Pause Button' : 'Play Button'}
        >
          {isPlaying ? (
            <PauseIcon className="text-3xl" />
          ) : (
            <PlayIcon className="text-3xl" />
          )}
        </button>
      ) : null}
    </div>
  );
};

export default MusicTrack;
