// src/modules/about/TopTracks.tsx
import React, { useEffect, useState } from 'react';
import useSWR from 'swr';
import fetcher from '~/lib/fetcher';
import MusicTrack from './MusicTrack';
import Router from 'next/router';
import { TopTracks } from '~/types/types';
import { PREVIEW_TRACK_COUNT } from '~/lib/constants';

const TopTracks: React.FC = () => {
  const { data } = useSWR<TopTracks>('/api/top-tracks', fetcher);
  const topTracks = data?.tracks;

  const [collapsed, setCollapsed] = useState(false);
  const [currentTrack, setCurrentTrack] = useState<{
    id: number | null;
    isPlaying: boolean;
    audio: HTMLAudioElement | null;
  }>({ id: null, isPlaying: false, audio: null });

  // Stop audio if route is changed
  Router.events.on('routeChangeComplete', () => {
    if (currentTrack?.audio) {
      currentTrack.audio.pause();
      currentTrack.audio.currentTime = 0;
    }
  });

  // Intial audio load when page is hydrated
  useEffect(() => {
    setCurrentTrack((c) => ({ ...c, audio: new Audio() }));
  }, []);

  useEffect(() => {
    // Call when track ends
    const onEnd = () => {
      setCurrentTrack((c) => ({ ...c, id: null, isPlaying: false }));
    };

    if (currentTrack.audio) {
      currentTrack.audio?.addEventListener('ended', onEnd);
      return () => {
        currentTrack.audio?.removeEventListener('ended', onEnd);
      };
    }
  }, [currentTrack.audio]);

  const handleToggleMusic = (trackId: number, audioUrl: string) => {
    const isNewTrack = currentTrack.id !== trackId;
    const isPlaying = isNewTrack || !currentTrack.isPlaying;

    if (currentTrack.audio) {
      if (isNewTrack) currentTrack.audio.src = audioUrl; // Switch to new song

      // Set volume to that track
      currentTrack.audio.volume = 0.15;

      // Play new track, or stop the current one
      isPlaying ? currentTrack.audio.play() : currentTrack.audio.pause();
    }

    // Apply changes
    setCurrentTrack((c) => ({ ...c, id: trackId, isPlaying }));
  };

  return (
    <section className="flex flex-col mb-6">
      <h2 className="font-medium text-black dark:text-primary-100 text-xl mb-3">
        Top 10 Tracks I listen To
      </h2>

      <div className="flex flex-col gap-4">
        {topTracks &&
          topTracks
            .map((track, i) => {
              return (
                <MusicTrack
                  key={i}
                  order={i + 1}
                  artist={track.artist}
                  title={track.title}
                  audioUrl={track.audioUrl}
                  thumbnailUrl={track.images[2].url}
                  onToggle={() => handleToggleMusic(i, track.audioUrl)}
                  isPlaying={currentTrack.id === i && currentTrack.isPlaying}
                />
              );
            })
            .slice(0, collapsed ? topTracks.length : PREVIEW_TRACK_COUNT)}
      </div>

      <button
        onClick={() => setCollapsed(!collapsed)}
        className="mx-auto mt-2 p-2 self-start text-secondary-accent hover:text-secondary-accent-hover font-medium"
      >
        {collapsed ? 'See Less' : 'See All'}
      </button>
    </section>
  );
};

export default TopTracks;

// src/routes/about/TopTracks.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import Headline from '$lib/components/nav/Headline.svelte';
	import { onMount, onDestroy } from 'svelte';
	import MusicTrack from './MusicTrack.svelte';

	const PREVIEW_TRACK_COUNT = 3;
	const { tracks: tracksData } = $page.data;

	let isCollapsed = true;
	let isPlaying: undefined | string;
	let audio: undefined | HTMLAudioElement;

	$: tracks = tracksData.slice(0, isCollapsed ? PREVIEW_TRACK_COUNT : tracksData.length);

	const playTrackAudio = (trackId: string, audioUrl: string) => {
		if (!audio) return;

		audio.src = audioUrl;

		if (!isPlaying || isPlaying !== trackId) {
			isPlaying = trackId;
			audio.play();
		} else {
			isPlaying = undefined;
			audio.pause();
		}
	};

	// Event listener
	const onEnd = () => {
		isPlaying = undefined;
	};

	onMount(() => {
		audio = new Audio();
		audio.volume = 0.15;

		audio?.addEventListener('ended', onEnd);
	});

	onDestroy(() => {
		// Stop music on route navigation
		audio?.pause();
		audio?.removeEventListener('ended', onEnd);
	});
</script>

<section class="mb-6 flex flex-col">
	<Headline level="2" class="mb-3">Top 10 Tracks I listen To</Headline>
	<div class="flex flex-col gap-4">
		{#if tracks}
			{#each tracks as track, i}
				<MusicTrack
					order={i + 1}
					artist={track.artist}
					title={track.title}
					audioUrl={track.audioUrl}
					thumbnailUrl={track.images[2]?.url}
					isPlaying={isPlaying === track.id}
					on:click={() => playTrackAudio(track.id, track.audioUrl)}
				/>
			{/each}
		{/if}
	</div>

	<button
		aria-expanded={!isCollapsed}
		class="mx-auto mt-2 self-start p-2 font-medium text-secondary-accent hover:text-secondary-accent-hover"
		on:click={() => (isCollapsed = !isCollapsed)}
	>
		Show {isCollapsed ? 'all' : 'less'}
	</button>
</section>
