// src/routes/Contact.svelte
<script>
	import Button from '$lib/components/Button.svelte';
	import Description from '$lib/components/Description.svelte';
	import Headline from '$lib/components/nav/Headline.svelte';
	import { EMAIL } from '$lib/constants';
</script>

<section>
	<Headline level="3" class="mb-2.5">Did I catch your attention?</Headline>

	<Description class="mb-5">
		Do you have a question, problem or idea that I can help you with? Do not hesitate to contact me.
	</Description>

	<div class="flex items-center gap-6">
		<Button href="/contact">Get in Touch</Button>

		<a href="mailto:{EMAIL}" class="font-medium text-zinc-500 hover:underline dark:text-zinc-400">
			{EMAIL}
		</a>
	</div>
</section>

// src/modules/index/Contact.tsx
import React from 'react';
import Link from 'next/link';
import Button from '~/ui/Button';

const Contact: React.FC = () => {
  return (
    <div className="mx-auto mb-12 w-full max-w-screen-xs px-6">
      <h3 className="mb-2.5 text-2xl font-medium text-black dark:text-primary-100">
        Did I catch your attention?
      </h3>

      <div className="mb-5 text-gray-600 dark:text-primary-300">
        Do you have a question, problem or idea that I can help you with? Do not
        hesitate to contact me.
      </div>

      <div className="flex items-center gap-8">
        <Link href="/contact">
          <Button>Get in Touch</Button>
        </Link>

        <a
          href={`mailto:${process.env.EMAIL}`}
          className="upp text-base font-medium text-gray-700 hover:underline dark:text-primary-200 xs:text-lg"
        >
          {process.env.EMAIL}
        </a>
      </div>
    </div>
  );
};

export default Contact;
